### ISSUE TITLE
plugin load fail

### ISSUE THREAD

**Issue by HenryHaoson** [Jedore/sentry-dingtalk#2]
log

```shell

Installing collected packages: sentry-dingtalk-jedore
Successfully installed sentry-dingtalk-jedore-1.0.7
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

Failed to load plugin 'dingtalk':
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2458, in resolve
    return functools.reduce(getattr, self.attrs, module)
AttributeError: module 'sentry_dingtalk.plugin' has no attribute 'DingtalkPlugin'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/sentry/runner/initializer.py", line 28, in register_plugins
    plugin = ep.load()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2450, in load
    return self.resolve()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2460, in resolve
    raise ImportError(str(exc)) from exc
ImportError: module 'sentry_dingtalk.plugin' has no attribute 'DingtalkPlugin'

```

**Comment by HenryHaoson** [comment]
sentry: 21.10.0

**Comment by Jedore** [comment]
Uh, I just tested sentry 21.5.1. Can you use version 21.5.1, I'm a little busy  recently. Ofcourse, I will try it as soon as possible.

**Comment by Jedore** [comment]
Uh, I just tested sentry 21.5.1. Can you use version 21.5.1, I'm a little busy  recently. Ofcourse, I will try it as soon as possible.

**Comment by HenryHaoson** [comment]
可以 close 了，虽然日志报错，但是插件是可以正常安装并且使用的。

**Comment by Jedore** [comment]
@HenryHaoson

我测试了一次： 卸载 21.5.1 （reset.h) 后， 安装 21.10.0， 并没有遇到你说的问题, 一次成功
```bash
[root@centos7 onpremise-21.10.0]# ./install.sh
此处省略。。。
[root@centos7 onpremise-21.10.0]#  vim sentry/requirements.txt
# Add plugins here
sentry-dingtalk-jedore

[root@centos7 onpremise-21.10.0]# docker-compose build
smtp uses an image, skipping
memcached uses an image, skipping
redis uses an image, skipping
postgres uses an image, skipping
zookeeper uses an image, skipping
kafka uses an image, skipping
clickhouse uses an image, skipping
geoipupdate uses an image, skipping
snuba-api uses an image, skipping
snuba-consumer uses an image, skipping
snuba-outcomes-consumer uses an image, skipping
snuba-sessions-consumer uses an image, skipping
snuba-transactions-consumer uses an image, skipping
snuba-replacer uses an image, skipping
snuba-subscription-consumer-events uses an image, skipping
snuba-subscription-consumer-transactions uses an image, skipping
symbolicator uses an image, skipping
web uses an image, skipping
cron uses an image, skipping
worker uses an image, skipping
ingest-consumer uses an image, skipping
post-process-forwarder uses an image, skipping
subscription-consumer-events uses an image, skipping
subscription-consumer-transactions uses an image, skipping
relay uses an image, skipping
nginx uses an image, skipping
Building snuba-cleanup
Sending build context to Docker daemon  3.584kB
Step 1/5 : ARG BASE_IMAGE
Step 2/5 : FROM ${BASE_IMAGE}
 ---> 515f5eaef539
Step 3/5 : RUN apt-get update && apt-get install -y --no-install-recommends cron &&     rm -r /var/lib/apt/lists/*
 ---> Using cache
 ---> 5e5b63b86482
Step 4/5 : COPY entrypoint.sh /entrypoint.sh
 ---> Using cache
 ---> c65ca48acaba
Step 5/5 : ENTRYPOINT ["/entrypoint.sh"]
 ---> Using cache
 ---> cdbc95bae8bb
Successfully built cdbc95bae8bb
Successfully tagged snuba-cleanup-onpremise-local:latest
Building snuba-transactions-cleanup
Sending build context to Docker daemon  3.584kB
Step 1/5 : ARG BASE_IMAGE
Step 2/5 : FROM ${BASE_IMAGE}
 ---> 515f5eaef539
Step 3/5 : RUN apt-get update && apt-get install -y --no-install-recommends cron &&     rm -r /var/lib/apt/lists/*
 ---> Using cache
 ---> 5e5b63b86482
Step 4/5 : COPY entrypoint.sh /entrypoint.sh
 ---> Using cache
 ---> c65ca48acaba
Step 5/5 : ENTRYPOINT ["/entrypoint.sh"]
 ---> Using cache
 ---> cdbc95bae8bb
Successfully built cdbc95bae8bb
Successfully tagged snuba-cleanup-onpremise-local:latest
Building symbolicator-cleanup
Sending build context to Docker daemon  3.584kB
Step 1/5 : ARG BASE_IMAGE
Step 2/5 : FROM ${BASE_IMAGE}
 ---> 64ccdf50243f
Step 3/5 : RUN apt-get update && apt-get install -y --no-install-recommends cron &&     rm -r /var/lib/apt/lists/*
 ---> Using cache
 ---> a8228d6fd131
Step 4/5 : COPY entrypoint.sh /entrypoint.sh
 ---> Using cache
 ---> adbd06659599
Step 5/5 : ENTRYPOINT ["/entrypoint.sh"]
 ---> Using cache
 ---> 28142852bcb1
Successfully built 28142852bcb1
Successfully tagged symbolicator-cleanup-onpremise-local:latest
Building sentry-cleanup
Sending build context to Docker daemon  3.584kB
Step 1/5 : ARG BASE_IMAGE
Step 2/5 : FROM ${BASE_IMAGE}
 ---> cdf35bd3e60b
Step 3/5 : RUN apt-get update && apt-get install -y --no-install-recommends cron &&     rm -r /var/lib/apt/lists/*
 ---> Using cache
 ---> 01ac6986de04
Step 4/5 : COPY entrypoint.sh /entrypoint.sh
 ---> Using cache
 ---> 0842a69cc69e
Step 5/5 : ENTRYPOINT ["/entrypoint.sh"]
 ---> Using cache
 ---> 03cfeb087594
Successfully built 03cfeb087594
Successfully tagged sentry-cleanup-onpremise-local:latest
[root@centos7 onpremise-21.10.0]# docker-compose up -d
Starting sentry_onpremise_clickhouse_1           ... done
Starting sentry_onpremise_symbolicator_1         ... done
Creating sentry_onpremise_geoipupdate_1          ... done
Starting sentry_onpremise_memcached_1            ... done
Starting sentry_onpremise_postgres_1             ... done
Starting sentry_onpremise_zookeeper_1            ... done
Starting sentry_onpremise_redis_1                ... done
Starting sentry_onpremise_smtp_1                 ... done
Creating sentry_onpremise_symbolicator-cleanup_1 ... done
Starting sentry_onpremise_kafka_1                ... done
Starting sentry_onpremise_snuba-api_1                                ... done
Creating sentry_onpremise_snuba-transactions-cleanup_1               ... done
Creating sentry_onpremise_snuba-cleanup_1                            ... done
Starting sentry_onpremise_snuba-sessions-consumer_1                  ... done
Starting sentry_onpremise_snuba-replacer_1                           ... done
Starting sentry_onpremise_snuba-subscription-consumer-events_1       ... done
Starting sentry_onpremise_snuba-outcomes-consumer_1                  ... done
Starting sentry_onpremise_snuba-transactions-consumer_1              ... done
Starting sentry_onpremise_snuba-subscription-consumer-transactions_1 ... done
Starting sentry_onpremise_snuba-consumer_1                           ... done
Creating sentry_onpremise_web_1                                      ... done
Creating sentry_onpremise_subscription-consumer-events_1             ... done
Creating sentry_onpremise_post-process-forwarder_1                   ... done
Creating sentry_onpremise_subscription-consumer-transactions_1       ... done
Creating sentry_onpremise_ingest-consumer_1                          ... done
Creating sentry_onpremise_worker_1                                   ... done
Creating sentry_onpremise_sentry-cleanup_1                           ... done
Creating sentry_onpremise_cron_1                                     ... done
Creating sentry_onpremise_relay_1                                    ... done
Creating sentry_onpremise_nginx_1                                    ... done
```
![Screenshot_2](https://user-images.githubusercontent.com/17944025/141115549-fb9a9057-8bf9-4e6b-bd9f-183de4fcd304.png)
